### ISSUE TITLE
Create coordinate transformation

### ISSUE THREAD

**Issue by solinvic** [xRetry/cps-assign2#4]
Write a function which transforms the coordinates of a path based on reference points.

As inputs, it should take 3 corner points and a list of coordinates, representing the path (path shape: (num_points, 2)).
It should return the path in the same shape but with different values, such that all path points are inside the reference area.

**Comment by bjoernellens1** [comment]
already on it

**Comment by bjoernellens1** [comment]
uploaded the files, still a problem with rotation function. Should be an easy fix. Need to check that transformation is also working for general pivot points.
@xRetry

**Comment by bjoernellens1** [comment]
consider it done, still leaving open if there is room for improvement. Like adding a function to reverse the transform resulting in the Transformation Matrix. Could be useful for converting the initial measurements from robot arm?
@xRetry

**Comment by solinvic** [comment]
I want to use it like this:

https://github.com/xRetry/cps-assign2/blob/0a2f576e6567e833f627d4e619973f889056cd6d/main.py#L21

So I need following the following function:

https://github.com/xRetry/cps-assign2/blob/0a2f576e6567e833f627d4e619973f889056cd6d/coordinate_affine_transform.py#L78-L99

**Comment by solinvic** [comment]
I added my own version of the function. 
bfb52d5db12321fce74d3295bd01a830cbc4699e

It needs more testing though
